### ISSUE TITLE
One Observation Excluded from Both Train and Test Sets

### ISSUE THREAD

**Issue by htdbui** [julianfaraway/LMP#10]
https://github.com/julianfaraway/LMP/blame/f73109122851b7e971de30e546ea0c9f87032e59/pyscripts/shrink.py#L133

The "trainmeat" dataset contains data from the first row to the 172nd row, while the "testmeat" dataset includes data from the 174th to the 215th row. The 173rd row is excluded.

It is so because trainmeat = meatspec.iloc[:172,] does not contain the value meatspec.iloc[172] and testmeat = meatspec.iloc[173:,] starts from value meatspec.iloc[173]. As a result, the value meatspec.iloc[172] is missed.

**Comment by julianfaraway** [comment]
Confirmed. I have edited the script to correct this. This results in small changes to subsequent calculations.
