### ISSUE TITLE
Wrong index

### ISSUE THREAD

**Issue by htdbui** [julianfaraway/LMP#5]
https://github.com/julianfaraway/LMP/blob/d43ebe5ed6a2faa8284a9a41ddebd4e0be619c1d/pyscripts/explanation.py#L94

In the book, we analyze the initial pair of matches, specifically focusing on cases 3 and 212. The corresponding code should be:

newhamp.iloc[[3, 212],[0, 6, 11]]

Additionally, there is no pair involving cases 76 and 84 in the results.

**Comment by julianfaraway** [comment]
You are correct - I have fixed this. Thanks.
