### ISSUE TITLE
Unused argument in sm.RLM function

### ISSUE THREAD

**Issue by htdbui** [julianfaraway/LMP#6]
There will be a warning related to the data keyword argument in the sm.RLM function. The data argument is not recognized by sm.RLM

https://github.com/julianfaraway/LMP/blame/dfe9d204c5c496a6054fb71f7ee199fb06e0666b/pyscripts/errprob.py#L228

**Comment by julianfaraway** [comment]
Yes. The argument is now redundant and I have removed it. Thanks.
